spring:
  profiles:
    active: dev

  mvc:
    favicon:
      enabled: true

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database: H2
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    data: classpath:movies.sql,classpath:links.sql,classpath:ratings.sql,classpath:tags.sql
    schema: classpath:schema.sql
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:soa_service_api
    username: root
    password: root
    connection-timeout: 5000